### PR TITLE
deb-pkg: Delete the firmware folder

### PR DESCRIPTION
**Pull request by hufenglin**
Look for firmware from the filesystem.

Signed-off-by: Hu Fenglin <fenglin.hu@intel.com>

### CODE REVIEW

**Review by gvancuts — APPROVED** [review]
LGTM!

One question, somewhat related to this: does the user now need to install additional firmware (not in the existing `linux-firmware` package in order to be able to use all the graphics capabilities with ACRN (on all supported platforms)?

**Comment by wenlingz** [comment]
@hufenglin please add Tracked-on info, thanks

**Comment by hufenglin** [comment]
> LGTM!
> 
> One question, somewhat related to this: does the user now need to install additional firmware (not in the existing `linux-firmware` package in order to be able to use all the graphics capabilities with ACRN (on all supported platforms)?

If the firmware is not found in the file system. Download the latest firmware to the host /lib/firmware/ directory. The latest firmware should be downloaded from https://01.org/linuxgraphics/downloads/firmware.

**Comment by gvancuts** [comment]
> If the firmware is not found in the file system. Download the latest firmware to the host /lib/firmware/ directory. The latest firmware should be downloaded from https://01.org/linuxgraphics/downloads/firmware.

If this is a reality today, we need to add this to our documentation.

/cc @NanlinXie @dbkinder

**Pull request merged**
