### PR TITLE
Update rt config

### PR DESCRIPTION
**Pull request by gvancuts**

### CODE REVIEW

**Comment by gvancuts** [comment]
@NanlinXie who should review and approve this?

**Comment by gvancuts** [comment]
Ping?

**Comment by dbkinder** [comment]
How does this impact (if any), our instructions for how to build the acrn-kernel (in the Getting Started Guide):
```
cd ~/acrn-work/acrn-kernel
cp kernel_config_service_vm .config
make olddefconfig
make -j $(nproc) deb-pkg
```

**Comment by gvancuts** [comment]
> Hi @gvancuts, from https://lwn.net/Articles/397363/ it seems that make savedefconfig reads current configuration (on build machine) and save it as a minimal configuration, which means that building kernel on different build machine may result in different configs. Could you please explain a little bit more?

`make savedefconfig` reads the current configuration (in `.config`) and turns that into a minimal config file, i.e. it only keeps the values that are different than the default values. Re-using that file on a different build machine will generate the same configuration than the one you started with. The advantage is that the file is a lot more readable and concise.

**Comment by gvancuts** [comment]
> How does this impact (if any), our instructions for how to build the acrn-kernel (in the Getting Started Guide):

It does not impact the instructions. Just that the `kernel_config_service_vm` file is more concise and readable.

**Comment by yfliuuu** [comment]
Changes LGTM. @lifeix Could you please also review?

**Pull request merged**
