### PR TITLE
config: switch the security framework to AppArmor

### PR DESCRIPTION
**Pull request by gvancuts**
Ubuntu (used by default as the Service VM OS) security framework
is AppArmor. The current kernel config uses SELinux but that causes
problems with some snap software packages.

Tracked-On: projectacrn/acrn-hypervisor#4975
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by wenlingz** [comment]
@gvancuts  please rebase your code because of conflict

**Comment by gvancuts** [comment]
> @gvancuts please rebase your code because of conflict

Done

**Comment by wenlingz** [comment]
@gvancuts  please rebase your code, thanks

**Comment by dbkinder** [comment]
@wenlingz geoffroy is on leave until mid-August

**Comment by gvancuts** [comment]
> @gvancuts please rebase your code, thanks

Finally got around to doing it... better late than never ;-)

**Comment by ionutnechita** [comment]
Hi @gvancuts,

Can we let it merge?

**Comment by gvancuts** [comment]
> Can we let it merge?

I cannot do that myself, I need approval from the maintainer(s). There is also a failure for the build but I need someone to dig up the actual log to see what's failing. My changes are just a kernel config options change, and I thought the Yocto recipes would anyway use their own config fragments but perhaps that's not the case.

**Review by shuox — COMMENTED** [review]
Why delete other config options?

**Comment by gvancuts** [comment]
> Why delete other config options?

This is the result of running `make savedefconfig` which creates a minimal config instead of keeping the exhaustive list of options (regardless of whether they are set or not). Running `make olddefconfig` after copying that file into `.config` will actually lead to the same kernel config. It just makes it easier (because shorter) to read the kernel config,

**Comment by shuox** [comment]
OK. Make sense. But we should make sure the EB services can work with it (and the document is right).

@wenlingz What's your opinion?

**Comment by gvancuts** [comment]
> 
> 
> OK. Make sense. But we should make sure the EB services can work with it (and the document is right).
> 
> @wenlingz What's your opinion?

@wenlingz ping?

**Comment by wenlingz** [comment]
> > OK. Make sense. But we should make sure the EB services can work with it (and the document is right).
> > @wenlingz What's your opinion?
> 
> @wenlingz ping?

If @NanlinXie  agree, no problem for me, thanks

**Review by shuox — APPROVED** [review]

**Pull request merged**
