### PR TITLE
kernel: Compile in USB XHCI drivers (default modules)

### PR DESCRIPTION
**Pull request by zds100**
Removed the dedicated partition mode uos kernel config file.
    Now sharing mode and partition mode use the same UOS kernel config file
    kernel_config_uos.
    The USB XHCI drivers need to be built-in in order to boot to a root filesystem on
    a USB Mass Storage Device.

Change-Id: I0e7f6cea273c35347a122bf41999040743ecf026
Tracked-On: projectacrn/acrn-hypervisor#1756
Signed-off-by: dongshen <dongsheng.x.zhang@intel.com>

### CODE REVIEW

**Comment by zds100** [comment]
Split into 2 commits

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by wenlingz** [comment]
OK to verify

**Comment by lijinxia** [comment]
OK to verify

**Pull request merged**
