### PR TITLE
/drm/i915/gvt: Wrong enable_pvmmio value after vgpu reset

### PR DESCRIPTION
**Pull request by psun3x**
vGPU reset will re-read pvmmio value from i915.params, but get
wrong value because using a bool type varible to store a u32 value.

Tracked-On: projectacrn/acrn-kernel#3622
Signed-off-by: Sun Peng <peng.p.sun@intel.com>
Review-by: He Min <min.he@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Can one of the admins verify this patch?

**Comment by yakuizhao** [comment]
Will you please help to update your patch as the acrn-kernel is rebased to GitHub.com/intel/Linux-intel-lts.git?
Thanks

**Comment by yakuizhao** [comment]
Will you please help to update your patch as the acrn-kernel is rebased to GitHub.com/intel/Linux-intel-lts.git?
Thanks

**Comment by wenlingz** [comment]
@psun3x please rebase your code, thanks

**Comment by acrnsi** [comment]
This branch has conflicts that must be resolved.The pr need rebase

**Comment by wenlingz** [comment]
close it because master has switched to 5.4

**Pull request closed without merging**
