### PR TITLE
Added i915/kbl_dmc_ver1_04.bin firmware in kernel config

### PR DESCRIPTION
**Pull request by ionutnechita**
Description
 - without this firmware, dmesg report warnings
   Failed to load DMC firmware i915/kbl_dmc_ver1_04.bin.
   Disabling runtime power management.

Change-Id: I35cd2debe8ab2bf8bd9d2e2039486939600c8680
Signed-off-by: Ionut Nechita <ionut_n2001@yahoo.com>

### CODE REVIEW

**Comment by ionutnechita** [comment]
Hi @gvancuts,

Can you help me with a review of this commit?

**Review by gvancuts — APPROVED** [review]
This looks good to me! Thanks for the patch @ionutnechita !

**Comment by gvancuts** [comment]
@NanlinXie , FYI (also needs a JIRA ID to be created)

**Comment by gvancuts** [comment]
Hi @ionutnechita , can you remove the `Change-Id` line in your commit message and use `Tracked-On: #330` instead? Thanks!

**Comment by ionutnechita** [comment]
Hi @gvancuts,

If it's ok for you, let's make the merge.

**Comment by gvancuts** [comment]
> If it's ok for you, let's make the merge.

I do not have the authority to do this.

@NanlinXie and @shuox can help approve.

(Note to whoever will merge this, please squash all three commits into one when doing so).

**Comment by ionutnechita** [comment]
Hi @gvancuts,

// (Note to whoever will merge this, please squash all three commits into one when doing so).
Sorry for this.

I did git commit --amend, and I didn't keep everything.
If it goes that way, then next time it's up to me to do it right.

Thanks for review.

**Comment by gvancuts** [comment]
Not a problem @ionutnechita 

If you want to fix this up, you can still do it as it's not been merged yet. In your master branch, do the following:
```
$ git rebase -i 42a5e48c3e11f0172dc73573c7f7db639079977b
-> Drop the commit that does not have the Tracked-On info -- see also below
$ git push -f <your remote>
```

```
pick 416d4cf39753 Added i915/kbl_dmc_ver1_04.bin firmware in kernel config
d 3f445801d48c Added i915/kbl_dmc_ver1_04.bin firmware in kernel config

# Rebase 42a5e48c3e11..c13905c69442 onto 42a5e48c3e11 (2 commands)
#
# Commands:
# p, pick <commit> = use commit
# r, reword <commit> = use commit, but edit the commit message
# e, edit <commit> = use commit, but stop for amending
# s, squash <commit> = use commit, but meld into previous commit
# f, fixup <commit> = like "squash", but discard this commit's log message
# x, exec <command> = run command (the rest of the line) using shell
# b, break = stop here (continue rebase later with 'git rebase --continue')
# d, drop <commit> = remove commit
# l, label <label> = label current HEAD with a name
# t, reset <label> = reset HEAD to a label
# m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
# .       create a merge commit using the original merge commit's
# .       message (or the oneline, if no original merge commit was
# .       specified). Use -c <commit> to reword the commit message.
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

**Comment by ionutnechita** [comment]
Hi @gvancuts,

Thanks for the information and help.

**Comment by ionutnechita** [comment]
Hi @gvancuts,

Observe this issue on this: Tracked-On/JIRA_GIT_ISSUE_Check — Fail

**Comment by gvancuts** [comment]
> Observe this issue on this: Tracked-On/JIRA_GIT_ISSUE_Check — Fail
> 
> It's normal?

Yes, kind of. We need to create a ticket in an internal JIRA instance and cross-reference those. The engineering team usually takes care of that but they did not get to it yet. I actually believe they'll want to file an issue on the `acrn-hypervisor` repo (instead of `acrn-kernel`) and use that in the `Tracked-On` info of your commit message. Let me see if I can make some of those while they're on leave for the Chinese New Year.

**Comment by gvancuts** [comment]
> > Observe this issue on this: Tracked-On/JIRA_GIT_ISSUE_Check — Fail
> > It's normal?
> 
> Yes, kind of. We need to create a ticket in an internal JIRA instance and cross-reference those. The engineering team usually takes care of that but they did not get to it yet. I actually believe they'll want to file an issue on the `acrn-hypervisor` repo (instead of `acrn-kernel`) and use that in the `Tracked-On` info of your commit message. Let me see if I can make some of those while they're on leave for the Chinese New Year.

Created https://github.com/projectacrn/acrn-hypervisor/issues/5744 for this (and [External_System_ID] ACRN-6976)

@ionutnechita , can you update your commit message to use this Github issue instead, i.e.:
`Tracked-On: projectacrn/acrn-hypervisor#5744`

**Comment by ionutnechita** [comment]
Ok for: Tracked-On: projectacrn/acrn-hypervisor#5744

**Comment by gvancuts** [comment]
@shuox @NanlinXie can you please help review this?

**Review by shuox — APPROVED** [review]

**Comment by ionutnechita** [comment]
Hi @gvancuts,

Could you help me here?

**Comment by gvancuts** [comment]
> Could you help me here?

Hi @ionutnechita , you needed to rebase your patch. I did that on your behalf and was able to force-push to your branch (I hope you don't mind I did that). There is no more merge conflict with master anymore. @wenlingz , can you remove the "code conflict" label?

**Comment by ionutnechita** [comment]
Hi @gvancuts,

Ok. Thanks for help.

**Pull request merged**
