### PR TITLE
Nuc kernel config

### PR DESCRIPTION
**Pull request by yakuizhao**
Add back the missing kernel config for Nuc
Tracked-On: projectacrn/acrn-hypervisor#1770
>NVME support
>RealTek PCI mmc card reader

### CODE REVIEW

**Comment by binbinwu1** [comment]
@yakuizhao It seems "Tracked-on" need to be changed to "Tracked-On", otherwise,  the integration system will send warning.

**Comment by yakuizhao** [comment]
It will be updated.

**Comment by wenlingz** [comment]
Have verified, it 's PASS

**Comment by ClaudZhang1995** [comment]
OK to verify

**Pull request merged**
