### PR TITLE
config: enable SD card driver for NUC SOS

### PR DESCRIPTION
**Pull request by conghuic**
CONFIG_MMC_REALTEK_PCI:
    Realtek PCI-Express SD/MMC Card Interface driver
CONFIG_MFD_RTSX_PCI:
    Driver for Realtek PCI-Express card reader

Signed-off-by: Conghui Chen <conghui.chen@intel.com>
Reviewed-by: Shuo Liu <shuo.a.liu@intel.com>
Acked-by: Zhao Yakui <yakui.zhao@intel.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
I guess you are not using this SD card to host the rootfs, are you?

**Comment by shuox** [comment]
Hi @gvancuts , yes, right. The SOS just cannot drive the SD card controller due to the lost of its driver. We we need add them as there are some cases around the SD card reader.

**Comment by shuox** [comment]
> I'm fine with this, the reason behind my question is that if the use-case is to use the SD card to host the SOS rootfs, it should be built-in (and not enabled as a module) since we do not use an initramfs.
Thanks for explanation. So far, we have no such usage.

**Comment by lijinxia** [comment]
Verified+1

**Pull request merged**
