### PR TITLE
acrn/vhm: Use the GFP_ATOMIC flag for allocating buffer from mempool …

### PR DESCRIPTION
**Pull request by yakuizhao**
…in vhm_inject_msi

Fix the issue caused by bc20d40bcd acrn/vhm: Use the mempool to allocate the buffer for hypercall parameter

the acrn_mempool_alloc is used to allocate the buffer in order to remove the
limitation that the acrn vhm can't work with VMAP_STACK. The vhm_irqfd_inject
will be called in eventfd_signal and the interrupt is disabled. In such case
the GFP_KERNEL will cause the below error:
BUG: sleeping function called from invalid context at mm/mempool.c:375
[ 1017.410403] in_atomic(): 1, irqs_disabled(): 1, pid: 861, name: vhost-842
[ 1017.412234] Preemption disabled at:
[ 1017.412243] [<ffffffff8829b822>] eventfd_signal+0x22/0x80

Tracked-On: projectacrn/acrn-hypervisor#3032
Signed-off-by: Zhao Yakui <yakui.zhao@intel.com>
Reviewed-by: Yin, FengWei <fengwei.yin@intel.com>

### CODE REVIEW

**Comment by acrnsi** [comment]
Ok to verify

**Comment by acrnsi** [comment]
@yakuizhao please rebase your code

**Comment by acrnsi** [comment]
@yakuizhao hi ,this branch has conflicts that must be resolved

**Comment by yakuizhao** [comment]
As this fix in this patch is merged into another patch, this PR will be closed.

**Pull request closed without merging**
