### PR TITLE
VBS: export vbs symbols

### PR DESCRIPTION
**Pull request by blegowsk**
This patch exports some vbs symbols for other modules to use.

Signed-off-by: Libin Yang <libin.yang@intel.com>

Please, see review here: https://lists.projectacrn.org/g/acrn-dev/topic/28241429#14900

### CODE REVIEW

**Comment by Mingyuan18** [comment]
@blegowsk , can't add "acrn-kernel" Issue ID. Need add "acrn-hypervisor" issue ID. thanks!

**Comment by libinyang** [comment]
> @blegowsk , can't add "acrn-kernel" Issue ID. Need add "acrn-hypervisor" issue ID. thanks!

I don't know whether there is issue filed for this patch. This patch is for the virtio device drivers that is built in module mode. In module mode, the virtio drivers need such symbols exported so that they can use them.

**Comment by blegowsk** [comment]
I created second PR https://github.com/projectacrn/acrn-kernel/pull/154 with Tracked-on for acrn-hypervisor issue. Please merge this patch or new https://github.com/projectacrn/acrn-kernel/pull/154 which ever one is correct.

**Comment by yakuizhao** [comment]
As another PR contains the similar fix, this PR will be closed.

**Pull request closed without merging**
