### PR TITLE
Acrnlog missing fix

### PR DESCRIPTION
**Pull request by KaigeFu**
Tracked-on: projectacrn/acrn-hypervisor#1801

### CODE REVIEW

**Comment by KaigeFu** [comment]
Tracked-On: projectacrn/acrn-hypervisor#1801

**Comment by KaigeFu** [comment]
@yakuizhao I have remove the smp_call_function_single related patch and update the typo fixing one.
Could you help review here?

**Comment by lijinxia** [comment]
@KaigeFu Please rebase and fix the conflicts!

**Comment by KaigeFu** [comment]
@yakuizhao @lijinxia I have create one new PR https://github.com/projectacrn/acrn-kernel/pull/144.

**Pull request closed without merging**
