### PR TITLE
config: add AUTOFS/AUTOFS4 module to kernel config

### PR DESCRIPTION
**Pull request by gvancuts**
Add the AUTOFS/AUTOFS4 module to the kernel configuration. This
is used by some user-space components such as automount. A
non-fatal error appears in dmesg when such module is not available:
"systemd[1]: Failed to find module 'autofs4'". Adding this module
eliminates this failure.

Tracked-On: #324
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
@gvancuts , please update Tracked on information "projectacrn/acrn-hypervisor#5735" in the commit message to fix tracked on issue.  And please rebase this PR based on https://github.com/projectacrn/acrn-kernel/pull/297, we need verify these two kernel config change together with GSG document before this two patches are merged.

**Comment by gvancuts** [comment]
Hi @NanlinXie , I've updated the commit message and I _hope_ I correctly rebased this on top of #297. You should be able to merge them one after the other (first #297 and then this one). Let me know if you have any issue and I'll fix them! Thanks!

**Review by shuox — APPROVED** [review]

**Comment by wenlingz** [comment]
@gvancuts  please rebase this PR, thanks

**Comment by gvancuts** [comment]
> @gvancuts please rebase this PR, thanks

Done. Thanks

**Pull request merged**
