### PR TITLE
release MSIX resource before unload uio driver

### PR DESCRIPTION
**Pull request by yonghuah**
MSI-x resource should be released when uio_pci_generic
 driver is unloaded.

Tracked-On: projectacrn/acrn-hypervisor#5889
Signed-off-by: Yonghua Huang <yonghua.huang@intel.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
Can you just fix the typo in your commit message? "resourece" -> "resource"

**Comment by yonghuah** [comment]
@gvancuts have updated this PR, thank you:)

**Review by gvancuts — APPROVED** [review]
Thanks!

**Comment by yonghuah** [comment]
@wenlingz can help export the fail log ? thanks.

**Review by shuox — APPROVED** [review]

**Pull request merged**
