### PR TITLE
Add support for hypercalls for sep and socwatch tool support

### PR DESCRIPTION
**Pull request by mchinth**
In order to support profiling in this patch we added:
New sbuf type for each tool is added
New hypercall for profiling operations [HC_PROFILING_OPS] added
List of profiling commands supported is added

Tracked-On: projectacrn/acrn-hypervisor#1409
Acked-by: Eddie Dong eddie.dong@intel.com
Signed-off-by: Manisha Chinthapally manisha.chinthapally@intel.com

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by mchinth** [comment]
Tracked-On:   https://github.com/projectacrn/acrn-hypervisor/issues/1409

**Comment by mchinth** [comment]
Can anyone merge ?

**Comment by wenlingz** [comment]
OK to Verify

**Comment by ClaudZhang1995** [comment]
OK to Verify

**Comment by lijinxia** [comment]
OK to Verify

**Comment by mchinth** [comment]
Updated the Tracked-On information in commit message to #1409.

**Comment by anthonyzxu** [comment]
This patch should not cause below failure, I saw unrelated failure twice recently, what's the root cause?

New errors/warnings found, please fix them:
==============================================

../../acrn-kernel/drivers/gpu/drm/i915/gvt/mpt.h:54: warning: No description found for parameter 'dev'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/mpt.h:54: warning: No description found for parameter 'gvt'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/mpt.h:54: warning: No description found for parameter 'ops'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/mpt.h:67: warning: No description found for parameter 'dev'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/mpt.h:67: warning: No description found for parameter 'gvt'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/mpt.h:83: warning: No description found for parameter 'vgpu'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/mpt.h:99: warning: No description found for parameter 'vgpu'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/mpt.h:119: warning: No description found for parameter 'vgpu'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/mpt.h:226: warning: No description found for parameter 'gfn'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/mpt.h:226: warning: Excess function parameter 'gpfn' description in 'intel_gvt_hypervisor_gfn_to_mfn'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/cfg_space.c:66: warning: No description found for parameter 'vgpu'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/cfg_space.c:66: warning: No description found for parameter 'off'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/cfg_space.c:66: warning: No description found for parameter 'src'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/cfg_space.c:66: warning: No description found for parameter 'bytes'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/cfg_space.c:100: warning: No description found for parameter 'vgpu'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/cfg_space.c:100: warning: No description found for parameter 'offset'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/cfg_space.c:100: warning: No description found for parameter 'p_data'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/cfg_space.c:100: warning: No description found for parameter 'bytes'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/cfg_space.c:335: warning: No description found for parameter 'vgpu'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/cfg_space.c:335: warning: No description found for parameter 'offset'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/cfg_space.c:335: warning: No description found for parameter 'p_data'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/cfg_space.c:335: warning: No description found for parameter 'bytes'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/mmio.c:47: warning: No description found for parameter 'gpa'
../../acrn-kernel/drivers/gpu/drm/i915/gvt/mmio.c:234: warning: No description found for parameter 'dmlr'

make[1]: *** [Makefile:57: html] Error 1
make[1]: Leaving directory '/workspace/acrn-hypervisor/doc'
make: *** [Makefile:38: doc] Error 2

**Comment by dbkinder** [comment]
The doc build failure is a problem with an update in the ACRN-kernel repo, as tracked by issue #119

**Pull request merged**
