### PR TITLE
Configruations: convert to minimal config files

### PR DESCRIPTION
**Pull request by gvancuts**
Use 'make savedefconfig' to convert the extensive kernel configuration files
to simplified ones.

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by dbkinder** [comment]
@gvancuts You should add some appropriate reviewers

**Comment by yfliuuu** [comment]
@gvancuts Same question as PR #369

**Comment by gvancuts** [comment]
> @gvancuts Same question as PR #369

Same answer :-))

**Comment by lifeix** [comment]
LGTM

**Pull request merged**
