### PR TITLE
r8169: enable r8169 driver for UOS

### PR DESCRIPTION
**Pull request by ghost**
UP2 and APL-NUC use realtek NIC, enabling corresponding driver for it.

Tracked-On: projectacrn/acrn-hypervisor#2643
Signed-off-by: Tw <wei.tan@intel.com>
Reviewed-by: Zhao Yakui <yakui.zhao@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com>

### CODE REVIEW

**Comment by NanlinXie** [comment]
Can one of the admins verify this patch?

**Comment by acrnsi** [comment]
OK to verify

**Comment by wenlingz** [comment]
@totoroow please modify the Tracked-On info,thanks

**Comment by totoroow** [comment]
@wenlingz Done.

**Pull request merged**
