### PR TITLE
xfs: Added XFS support in config files

### PR DESCRIPTION
**Pull request by ionutnechita**
Tracked-On: https://github.com/projectacrn/acrn-hypervisor/issues/7667
Signed-off-by: Ionut Nechita <ionut_n2001@yahoo.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
The changes look good to me! Can you change the `Bug:` tag to `Tracked-On:`?

Note: I migrated your issue over to `acrn-hypervisor`.

**Comment by yfliuuu** [comment]
The change looks good to me.

**Review by gvancuts — APPROVED** [review]
Thanks!

**Comment by ionutnechita** [comment]
Hi @gvancuts,

It's possible to merge this in main/master branch?

**Comment by ionutnechita** [comment]
Hi @yfliuuu,

I did a rebase today, it should be right now.

**Review by gvancuts — APPROVED** [review]
Thanks @ionutnechita

**Pull request merged**
